### ISSUE TITLE
Criar lab de CronJob

### ISSUE THREAD

**Issue by luszczynski** [redhat-sa-brazil/workshop-openshift#42]
Luciano fez para algum cliente um exemplo de cronjob.

1 - Cria alpine com curl
```
FROM alpine
RUN apk add --no-cache curl
ENTRYPOINT ["/usr/bin/curl"]
```

2 - publica no docker.io

3 - Cria cronjob com a imagem
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjobcurl
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:             
    spec:
      template:
        metadata:
          labels:          
            parent: "cronjobcurl"
        spec:
          containers:
          - name: curljob
            image: docker.io/lasher/alpinecurl
            command: ["curl",  "-v", "http://phpapp:8080"]
          restartPolicy: OnFailure
```

Sugiro utilizar isso como base para uma criação do lab de cronjob
